#Prject Euler Question 2

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def func_fib(x):
    n1 = 0
    n2 = 1
    n3 = 0
    list_fib = [0]
    result = 0
    for x in range(0, x):
        n3 = (n1 + n2)
        if (n3 >= 4e6):
            break
        if (n3 % 2 == 0):
            #print(n1, "+", n2, "=", n3)
            list_fib.append(n3)
        n1 = n2
        n2 = n3
    #print()
    #print(list_fib)
    #print(len(list_fib))
    #print()
    for y in list_fib:
        result += y
    print(result, "is the sum of the even valued fibonacci terms up to four million")
        

func_fib(x = 100)